# Generated by Django 3.2.5 on 2021-08-01 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_rename_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="description",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_organizer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_on",
        ),
        migrations.AlterField(
            model_name="user",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
